defaults: &defaults
  apikey: [APIKEY]
  almaurl: https://api-na.hosted.exlibrisgroup.com/almaws/v1
  institution: [INSTITUTION]
  alma: na01
  root_url: [root url]
  alma_auth_secret: [auth secret for Oauth]
  SOLR_URL: [solr url]

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults